database:
  server: your-server.region.rds.amazonaws.com
  name: your-database-name
  username: your-username
  password: your-password

aws:
  region: us-east-2
  instance_id: i-xxxxxxxxxxxxxxxxx

lambda:
  timeout: 900
  memory_size: 256