# Database configuration
database:
  connection_timeout: 30
  login_timeout: 30
  command_timeout: 300

# Lambda configuration
lambda:
  timeout: 900
  memory_size: 256
  handler: lambda_function.lambda_handler
  runtime: python3.8

# Export settings
export:
  chunk_size: 50000
  player_stats_chunk_size: 25000

# Logging configuration
logging:
  level: INFO
  format: "%(asctime)s - %(levelname)s - %(message)s"